#!/usr/bin/env bash

printf -v TIMESTAMP "%(%Y-%m-%dT%H:%M:%S%z)T" -1

function metadata()
{
    xprop -id "$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)" \
    | awk '$1 ~ /^(_NET_)?(WM_CLASS|WM_WINDOW_ROLE|WM_NAME|WM_PID)/'
}

# Capture a screenshot spanning all displays.
#
function screenshot()
{
    metadata > "$TIMESTAMP.txt"
    scrot "$TIMESTAMP.png"
}

# Capture a screenshot of the currently selected window.
#
function window-screenshot()
{
    metadata > "$TIMESTAMP.txt"
    scrot --focused "$TIMESTAMP.png"
}

function main()
{
    set -e -u -o pipefail

    mkdir -p ~/screenshots/
    cd ~/screenshots/

    case "${1:-}" in
      window)
        window-screenshot
      ;;
      "")
        screenshot
      ;;
      *)
        echo "Unrecognized screenshot type ($1)" >&2
        return 1
    esac
}

test "${BASH_SOURCE:-}" != "$0" || main "$@"
