#!/bin/sh
# This script is used to re-open files in the current Git repo that were
# edited. By default, it launches a text editor with all untracked or modified
# files, but untracked files may be elided by using "-m". The user may also
# specify additional files as command line arguments.
PATTERN="[MA?]"

while getopts hmV option; do
    case "$option" in
      m)
        PATTERN="[MA]"
      ;;
      \?|h|V)
        echo "Usage: git vi [-m] [FILENAME]..."
        echo
        echo "Options:"
        echo "  -m    Modified files only; do not include untracked files"
        test "$option" = "?" && exit 1 || exit 0
      ;;
    esac
done

shift "$((OPTIND - 1))"

(test "$#" -eq 0 || printf ' M %s\000' "$@"; git status --porcelain -z) \
| gawk -v RS='\000' -v PATTERN="$PATTERN" '
    $1 ~ PATTERN {
        printf "%s\000", substr($0, 4)
    }' \
| xargs -0 sh -c '${VISUAL:-${EDITOR:-vi}} < /dev/tty -- "$@"' --
