#!/usr/bin/env bash
# Usage: iterm [COMMAND [ARGUMENT]...]
#
# Launch an iTerm2 window using the default profile. The default profile's
# launch command may be overridden by specifying an alternative command the
# argument to this script.
set -e

# Convert a command and its arguments to an infix that can be used in
# AppleScript to run the command with iTerm2. This entails escaping single
# quotes, double quotes and backslashes in each argument then enclosing each
# escaped argument with single quotes and, finally, enclosing the concatenated
# escaped arguments with double quotes.
#
# Arguments:
# - $1: Command name.
# - $@: Optional list of command arguments.
#
function argv-to-iterm-applescript-infix()
{
    local argument

    printf 'command "'

    for argument in "$@"; do
        argument="${argument//\\/\\\\\\\\}"
        argument="${argument//\'/\\\\\'}"
        argument="${argument//\"/\\\"}"
        printf "'%s' " "$argument"
    done

    printf '"'
}

test "$#" -eq 0 || infix="$(argv-to-iterm-applescript-infix "$@")"
osascript -e "tell application \"iTerm2\"
    create window with default profile ${infix:-}
end tell"
