#!/bin/sh
set -e -u

capture_pane()
{
    tmux capture-pane -e -p -S - -E -1
    # Add a bold cyan separator to indicate which text is in the visible area.
    printf '\033[1m\033[36m~~~\033[0m\n'
    tmux capture-pane -e -p
}

main()
{
    # In the Less invocations, "+G +k" ensures the viewport used by Less
    # exactly matches the pane to make the transition seamless.
    if [ "${TMUX_PANE:-}" ]; then
        # When starting Less from a shell session, Less may switch to the
        # alternate screen which immediately clears the display, spoiling the
        # output of capture-pane. To work around this, the scrollback is dumped
        # to a file first instead of being piped directly to Less when this
        # command is run from a shell.
        trap 'rm -f -- "${tempfile:-}"' EXIT
        tempfile="$(mktemp)"
        capture_pane > "$tempfile"
        less +G +k "$@" -- "$tempfile"
    else
        capture_pane | less +G +k "$@"
    fi
}

main "$@"
