#!/bin/sh
set -e -f -u

if ! paths="$(which "$@")"; then
    echo "${0##*/}: one or more commands not found" >&2
    exit 1
fi

for path in $paths; do
    if [ "$(head -c 2 -- "$path")" != "#!" ]; then
        echo "$path: not a text script" >&2
        exit_code=1
    fi
done

test "${exit_code:-0}" -eq 0 || exit "$exit_code"
exec ${VISUAL:-${EDITOR:-vi}} $paths
