#!/bin/sh
exec > /dev/null 2>&1

. ~/.profile

xmodmap -e "remove mod4 = Hyper_L" \
        -e "remove Lock = Caps_Lock" \
        -e "keysym Caps_Lock = Hyper_L" \
        -e "add mod3 = Hyper_L"
xrdb -load "$EMUS/configuration/xrdb.ad"
xset s off -dpms
blackwalls

test -e "$HOME/.local.xsession" && . "$HOME/.local.xsession"

compton --daemon -C $(
    glxinfo | fgrep -q "direct rendering: Yes" && echo " --backend=glx"
)

st &
statusline -i -m -z US/Pacific | singleton fifo2rootname &

PATH="$EMUS/desktop-environment/scripts:$PATH"
singleton hid-monitor &
singleton media-control monitor &

until dwm; do sleep 1; done
kill -SIGHUP -$$
